- name: Setup emacs-plus homebrew tap
  homebrew_tap:
    name: d12frosted/emacs-plus
- name: Install Emacs
  homebrew:
    name: emacs-plus@27
    state: present
    install_options: --with-xwidgets --with-modern-icon-sexy-v1
- name: Create .emacs.d directory
  file:
    path: "~/.emacs.d"
    state: directory
- name: Init file
  copy:
    src: "{{ role_path }}/files/init.el"
    dest: "~/.emacs.d/init.el"
    force: yes
- name: Main config orgmode file
  copy:
    src: "{{ role_path }}/files/config.org"
    dest: "~/.emacs.d/config.org"
    force: yes
